app = 'cncars-service-bot'
primary_region = 'fra'

[build]

[deploy]
strategy = "rolling"
standby = false

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1