app = "cncars-service-bot"

[build]
builder = "paketobuildpacks/builder:base"

[env]
TOKEN = "7549988426:AAGZj8Jt9QWt1HeJhcCp5VgjP-XBCKtHQIc"  # Можно также через переменные Fly.io

[http_service]
internal_port = 8080
force_https = true
